### ISSUE TITLE
Question about Slip39: why not stack on top of BIP39

### ISSUE THREAD

**Issue by My1** [satoshilabs/slips#1013]
Considering all the problems in compatibility, I honestly wonder why not instead of Converting the Master Seed of Bip32 go for the BIP39 entropy. I mean that way you would have no problems going either way without any disadvantages, like crazy long share phrases or losing the Passphrases you used with the BIP39 seed.

especially considering SLIP39 is iirc not that widely supported especially in Hardware wallets of which I out of hand only know the 180€ Trezor T, I would say it's quite a lock-in effect when you cannot convert a SLIP39 to a BIP39 seed.

it also would have been quite fitting both have the number 39 to them AND being similar in what they do (encode a secret in a way humans can deal easier with it) they could also just have been made compatible

**Comment by prusnak** [comment]
Rationale is described in bullet 9 of https://github.com/satoshilabs/slips/blob/master/slip-0039.md#design-rationale

What you suggest makes use of a passphrase on the device impossible.

**Comment by My1** [comment]
why would that make the use of a passphrase impossible tho? I mean if SLIP39 would go into BIP39 entropy the passphrase would be perfectly valid to be added there, after all in BIP39 you take the seed and the passphrase and generate the BIP32 seed that way.

**Comment by prusnak** [comment]
Have you read the rationale?

**Comment by My1** [comment]
yes but the first 3 paragraphs explain how the implementation of slip is limiting, i.e. that when converting BIP39 TO SLIP39 that
1) the shares are going to be LONG due to the seed being 512 bits long
2) only one BIP32 seed can be used so either no passphrase or one specific one
that it is better to start new to not accidentially reveal the BIP39 original if that's what you started with and that converting the SLIP39 to BIP39 is not possible at all because PBKDF2.

the 4th paragraph talking about actual concerns doesnt even mention the passphrase at all, it just says that there is no concern of lock-in and no direct reason of why not just stacking them.
In fact it basically just says that the user can just use a software wallet and send funds over, which I laid out in the reply above.
