### ISSUE TITLE
SLIP-0039: can we omit Gt, g and t in the format of the shares?

### ISSUE THREAD

**Issue by gzm55** [satoshilabs/slips#1156]
For combining the final EMS, we should only need the group index (GI) and the member index (I). Is there any reason to include the group threshold (Gt), group count (g), and member threshold (t) in the final shares?

**Comment by prusnak** [comment]
> Is there any reason to include the group threshold (Gt), group count (g), and member threshold (t) in the final shares?

We want to have the best user experience and we want to be able to show the correct group threshold, group count and member threshold immediately after you use the first share.
