### ISSUE TITLE
version bytes for p2tr

### ISSUE THREAD

**Issue by blockonomics** [satoshilabs/slips#1194]
Hi,

Since everyone is preparing for p2tr addresses, it would be good to have version bytes similar to [slip0132](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) for bech32m. 

Would be good to have the version bytes standardized early on [inside bip86](https://github.com/bitcoin/bips/blob/master/bip-0086.mediawiki) before wallets start implementing P2TR.  This will avoid issues like [this](https://github.com/LedgerHQ/ledger-live-desktop/issues/2527#issuecomment-779674320) where lots of wallets are still not using version bytes

**Comment by andrewkozlik** [comment]
We intend to solve this in Trezor using [output descriptors](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md). See for example https://github.com/trezor/trezor-firmware/blob/master/tests/device_tests/test_descriptors.py.

**Comment by prusnak** [comment]
Correct, descriptors are the way to go.

**Comment by blockonomics** [comment]
Just to clarify this will apply to the existing ypub/zpub wallets in trezor. So on show xpub screen something like `wpkh(xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8)   ` will be shown ?
![trezor2](https://user-images.githubusercontent.com/22165583/142215736-0da7ceab-c7ad-4d06-a5ef-f3a729725c50.jpg)

**Comment by prusnak** [comment]
> So on show xpub screen something

Yes, `p2tr(xpub..../<0;1>/*)` will be shown

**Comment by blockonomics** [comment]
Can you please give exact test vector that also work on your explorer https://btc1.trezor.io/ 

> We intend to solve this in Trezor using [output descriptors](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md). See for example https://github.com/trezor/trezor-firmware/blob/master/tests/device_tests/test_descriptors.py.
Descriptors page mentioned here are not reachable

**Comment by prusnak** [comment]
> Can you please give exact test vector that also work on your explorer

Check https://github.com/satoshilabs/slips/blob/master/slip-0014.md#bitcoin-taproot--p2tr--bip86

Either this

[`tr(xpub6Bw885JisRbcKmowfBvMmCxaFHodKn1VpmRmctmJJoM8D4DzyP4qJv8ZdD9V9r3SSGjmK2KJEDnvLH6f1Q4HrobEvnCeKydNvf1eir3RHZk)`](https://btc1.trezor.io/xpub/tr(xpub6Bw885JisRbcKmowfBvMmCxaFHodKn1VpmRmctmJJoM8D4DzyP4qJv8ZdD9V9r3SSGjmK2KJEDnvLH6f1Q4HrobEvnCeKydNvf1eir3RHZk))

or this

 [`tr([5c9e228d/86'/0'/0']xpub6Bw885JisRbcKmowfBvMmCxaFHodKn1VpmRmctmJJoM8D4DzyP4qJv8ZdD9V9r3SSGjmK2KJEDnvLH6f1Q4HrobEvnCeKydNvf1eir3RHZk/<0;1>/*)#4swej4wz`](https://btc1.trezor.io/xpub/tr([5c9e228d/86'/0'/0']xpub6Bw885JisRbcKmowfBvMmCxaFHodKn1VpmRmctmJJoM8D4DzyP4qJv8ZdD9V9r3SSGjmK2KJEDnvLH6f1Q4HrobEvnCeKydNvf1eir3RHZk/%3C0;1%3E/*))

works
