### ISSUE TITLE
Create list of reserved SLIP-0173 prefixes

### ISSUE THREAD

**Issue by sunnya97** [satoshilabs/slips#1228]
I feel we should create a list of reserved bech32 prefixes that no new chain can take.  For example, things like `btc` or `eth`.

Even though Ethereum does not currently use bech32 for addresses, we don't know if it might in the future.  There have been proposals to such effect in the past.

And even though Bitcoin uses `bc` not `btc`, `btc` should be unclaimable as it would cause much confusion if used by something other than Bitcoin.

**Comment by prusnak** [comment]
There is no need for this.

First of all, I will simply not merge PR if the proposed change is dubious.

Second of all, the coin can still ignore the recommendation.
