### ISSUE TITLE
SLIP-044 needs to become "many to one"

### ISSUE THREAD

**Issue by sunnya97** [satoshilabs/slips#1229]
Currently the structure of the SLIP-044 repo is that each new chain corresponds to a single BIP44 path.  

However, in the current state of blockchains we live in today, multiple chains may often share the same SLIP-044 path.  This is usually done to have address compatibility across chains.  For example, the same private key often is intended to generate the same address on multiple EVM-compatible chains such as Ethereum, Binance Smart Chain, etc.

Within the Cosmos ecosystem (in which I work), we are actually urging all the chains built using our stack to use the standardized bip44 path of `118`.  Reasons here:  https://medium.com/chainapsis/keplr-explained-coin-type-118-9781d26b2c4e

When building a chain that reuses a BIP44 path, the current standard is to not add anything to the SLIP-044 repo.  However, this makes the work for integrators more difficult, as this repo is used by many as the source of truth for bip44 paths, and it is unclear if a chain has a non-unique path, or simply has not updated this repo yet.

**Comment by sunnya97** [comment]
Related issue:  https://github.com/satoshilabs/slips/pull/1203#issuecomment-1001298888

**Comment by prusnak** [comment]
BIP44 and SLIP44 exist to isolate the private keys of different chains.

If there are some chains that do not want this feature, I guess there is no way to stop them reusing the value, but there is very little incentive to add them all to the SLIP-0044 list. Let's just keep the main one for each entry.
