### ISSUE TITLE
want add c4ei

### ISSUE THREAD

**Issue by c4ei** [satoshilabs/slips#1257]
dear satoshilabs.

how can i add [ https://github.com/c4ei/slips/blob/master/slip-0044.md ]
blow line ?
21004 | 0x8000520c | C4EI   | [c4ei](https://c4ei.net)

**Comment by prusnak** [comment]
just send a pull request: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
