### ISSUE TITLE
How do add a new coin?

### ISSUE THREAD

**Issue by vanhalendlrband** [satoshilabs/slips#1397]
Need to add Neoxa and find its hex

**Comment by prusnak** [comment]
Just send a pull request where you edit the slip-0044.md file

**Comment by vanhalendlrband** [comment]
Is the coin type number just arbitrary? I dont work for Neoxa i just need it because im trying to recover a wallet and i need this hex value to add to iancolemans tools

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prusnak** [comment]
Yes, arbitrary, but it's good to choose the first available
