### ISSUE TITLE
retry on failure secp256k1

### ISSUE THREAD

**Issue by dvc94ch** [satoshilabs/slips#1409]
is BIP32 modified for the secp256k1 curve too? what should a correct implementation do in case of failure on secp256k1?

**Comment by prusnak** [comment]
Quoting from BIP32:

In case parse256(IL) ≥ n or ki = 0, the resulting key is invalid, and one should proceed with the next value for i. (Note: this has probability lower than 1 in 2^127.)

**Comment by prusnak** [comment]
SLIP-0010 describes how to derive private and public key pairs for curve types different from secp256k1.

**Comment by steed717** [comment]
> Quoting from BIP32:
> 
> In case parse256(IL) ≥ n or ki = 0, the resulting key is invalid, and one should proceed with the next value for i. (Note: this has probability lower than 1 in 2^127.)

So, if using BIP32 and exactly implementing the error handling above, that will mean BIP32 may skip some index in the key tree, which SLIP 10 will not. Does this break the compatibility among them, since the BIP32 tree will be different than SLIP10 key tree?

**Comment by prusnak** [comment]
> Does this break their compatibility since the BIP32 tree will differ from the SLIP10 key tree? 

BIP32 is defined for secp256k1 curve

SLIP10 is defined for curves that are not secp256k1

There never was a compatibility

**Comment by steed717** [comment]
> > Does this break their compatibility since the BIP32 tree will differ from the SLIP10 key tree?
> 
> BIP32 is defined for secp256k1 curve
> 
> SLIP10 is defined for curves that are not secp256k1
> 
> There never was a compatibility
Sorry, confused you, when I am talking the skip indes N, I mean when SLIP10 uses secpk1,  the key tree will differ. What will happen, if the the SLIP10 k1's key under the N subtree was used in BIP32 implementation? is it safe and will not break and fine to use the BIP32 implementation?

**Comment by steed717** [comment]
> You should not use SLIP10 with secp256k1
This isn't very clear.  See the statement form SLIP10
```
The supported curves are
    Curve = "Bitcoin seed" for the secp256k1 curve (this is compatible with BIP-0032).
    Curve = "Nist256p1 seed" for the NIST P-256 curve.
    Curve = "ed25519 seed" for the ed25519 curve.
```
Do you the secp256k1 generated from SLIP10 should not use in BIP32 application?

**Comment by andrewkozlik** [comment]
> You should not use SLIP10 with secp256k1

I have to say that I agree with @steed717. SLIP-10 is not entirely clear about this. Although several statements in the spec indicate that it is intended for curve types different from secp256k1, e.g. the abstract, there are at least two things in the spec that contradict this:
1. The already mentioned quote:
    > The supported curves are
    > - Curve = "Bitcoin seed" for the secp256k1 curve (this is compatible with BIP-0032).

    which is clearly untrue.
2. SLIP-10 includes test vectors for secp256k1, which seems strange if it's not intended to be used with secp256k1.

Finally, our own trezor-crypto actually uses SLIP-10 for secp256k1 key derivation. Of course, this is identical to BIP-32 with near certainty (probability greater than 1&minus;2<sup>&minus;127</sup> per derivation operation), but this only adds to the contradiction. @matejcik

**Comment by steed717** [comment]
k

**Comment by andrewkozlik** [comment]
For the record, we had a meeting on 27th February 2024 with @prusnak and @slush0 where we agreed that SLIP-10 should be updated to say that it also applies to the Bitcoin curve. I will update the spec accordingly.
