### ISSUE TITLE
Reference to non-existing AES section

### ISSUE THREAD

**Issue by super-e** [satoshilabs/slips#1444]
Hi,
I'm trying to understand the topic better, in the Shamir's Secret Sharing section there is a reference to AES document section 4.4, which does not exist in the FIPS-197 document. Which one should be the correct referenced section?
"see [AES](https://doi.org/10.6028/NIST.FIPS.197) sections 3.2, 4.1 and **4.4.**"
Thanks
-E-

**Comment by andrewkozlik** [comment]
Thanks for finding this @super-e ! The correct reference must be the multiplication section 4.2. Fixed in 40a55141e8ee8bc8fe90b091a44ab40408b42d58.
