### ISSUE TITLE
the problem with negligent waste of marketing budget funds

### ISSUE THREAD

**Issue by Kwaskoff** [satoshilabs/slips#1471]
you know that any Cosmos-SDK based coins are still not supported by Trezor
And Agoric are also not supported because it is a Cosmos-SDK based blockchain.
![Screenshot from 2022-12-19 14-11-43](https://user-images.githubusercontent.com/15308024/208437732-3d03ed65-21b6-4018-811e-8f7ffad5c911.png)
and for what reason did you spend your money on banner advertising in the Cosmos-SDK-based blockchain explorer?
![Screenshot from 2022-12-19 14-11-26](https://user-images.githubusercontent.com/15308024/208437868-59a8181d-0900-4020-88ee-e98afebac639.png)

I think it's not unwise. Thanks

**Comment by prusnak** [comment]
Thanks for the feedback.
