### ISSUE TITLE
SLIP44: add website

### ISSUE THREAD

**Issue by JayBitron** [satoshilabs/slips#1475]
Allow registration of tickers with only a valid website, for example if I have a mining pool or an crypto exchange, if someone registered a ticker X but there are two websites X.com and X.org and both of them are operate by diffident people but using same ticker: X, this confuse people, and anything can go wrong. So having an live website for each ticker is important.

**Comment by prusnak** [comment]
This is out of scope of what we are doing.

**Comment by JayBitron** [comment]
Can you describe that?

**Comment by prusnak** [comment]
> Can you describe that?

Yes. There is no need for us to maintain such list.
