### ISSUE TITLE
Duplicate Tickers

### ISSUE THREAD

**Issue by JayBitron** [satoshilabs/slips#1489]
How possibly did you allow duplicate tickers?

**Comment by prusnak** [comment]
Where?

**Comment by JayBitron** [comment]
https://github.com/satoshilabs/slips/issues/1474

**Comment by prusnak** [comment]
I don't see any duplicate tickers in SLIP-0044. Closing

**Comment by JayBitron** [comment]
do you want me to list them for you?

**Comment by JayBitron** [comment]
Hello? are you blind?

**Comment by JayBitron** [comment]
XCH -> ClearingHouse|Chia
CCN -> Cannacoin|ComputeCoin
NXT -> NXT|NxtMeta
BTA -> Bata|Btachain
MTR -> MasterTrader|Meter
FCT -> Factom Factoids|FirmaChain
BCO -> Bridgecoin|BitcoinOre
MONK -> Monkey Project|Monk
UC -> Ulord|Utopiacoin
XRD -> Redstone|Radiant|Radix DLT
ONE -> ONE|HARMONY-ONE
SBC -> SBC|Senior Blockchain
CPC -> Capricoin|CPChain
CMT -> Community|CyberMiles Token
CS -> Credits|Credits
RYO -> Ryo Currency|c0ban
BTCR -> Bitcoin Royale|BTCR
KTS -> Klimatas|Kratos
GLEEC -> GLEEC|GleecBTC
BSC -> Bitcoin Smart Contract|Binance Smart Chain
VAL -> Valorbit|Validator|Validity
BBC -> BigBang Core|Big Bitcoin|Babacoin
SUM -> Sumcoin|Solidum
TAO -> Tao|Bittensor
DYN -> Dynamo|Dynamic
CCC -> Commercio Cash Credit|CodeChain
DST -> DSTRA|DeStream
XEC -> eCash|eCash token
LBTC -> Lightning Bitcoin|Liquid BTC
DFI -> DeFiChain|DeFiChain EVM Network
SAFE -> SAFE|Safecoin

**Comment by prusnak** [comment]
Tickers in SLIP-0044 are not important since the reason for SLIP-0044 to exist is to assign BIP-44 paths.

**Comment by JayBitron** [comment]
wtf is wrong with you?

**Comment by prusnak** [comment]
This is your last comment in this repository since you cannot behave. Bye

**Comment by JayBitron** [comment]
you say something else everything https://github.com/satoshilabs/slips/issues/1474 go make up your mind
