### ISSUE TITLE
SLIP-0044: Add YadaCoin

### ISSUE THREAD

**Issue by pdxwebdev** [satoshilabs/slips#1585]
Coin name:
YadaCoin

Coin symbol:
YDA

A brief description of the coin and the blockchain it operates on:
YadaCoin is an identity blockchain to save relationships, and other identity information to be accessed across applications and devices.
This is a native coin with it's own blockchain written from scratch.

Any relevant links or references:
https://yadacoin.io
https://github.com/pdxwebdev/yadacoin

**Comment by prusnak** [comment]
added in 2a66e694e9083a222c21b38a0b163055e5903ff2

the number assigned to YDA is 657
