### ISSUE TITLE
SLIP-0039 fixed salt

### ISSUE THREAD

**Issue by juestr** [satoshilabs/slips#159]
Please explain why the fixed salt in the passphrase section is no hazard? It appears to me that either this creates a vulnerability to rainbow tables, or that PBKDF2 isn't necessary at all.

**Comment by prusnak** [comment]
It's work in progress, paragraph Passphrase is still work in progress.

--
Best Regards / S pozdravom,
 
Pavol Rusnak <stick@gk2.sk>


On Wed, Jan 3, 2018, at 2:38 AM, Jürgen Strobel wrote:
> Please explain why the fixed salt in the passphrase section is no
> hazard? It appears to me that either this creates a vulnerability to
> rainbow tables, or that PBKDF2 isn't necessary at all.> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/satoshilabs/slips/issues/159

**Comment by wigy-opensource-developer** [comment]
@prusnak @juestr So now the paragraph is complete with the optional password protection, right? So this issue can be closed.

**Comment by prusnak** [comment]
Right
