### ISSUE TITLE
Add Phoenix

### ISSUE THREAD

**Issue by Fluffynorth** [satoshilabs/slips#1681]
Coin name:
Phoenix Mainnet

Coin symbol:
PHX

A brief description of the coin and the blockchain it operates on:
The Phoenix Blockchain is the backbone for the Initiative. It is a Layer 1 EVM blockchain with gas fees capped at 1 gwei of Phoenix.

Any relevant links or references:
https://phoenixblockchain.org.
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-13381.json

**Comment by Fluffynorth** [comment]
How do I get coin_type bip # in order to commit for pr?

**Comment by prusnak** [comment]
Choose the next available
