### ISSUE TITLE
 Inquiry Regarding Deletion of SLIP-0084 (BIP84) Standard

### ISSUE THREAD

**Issue by wangyifan349** [satoshilabs/slips#1691]
Dear Repository Maintainers,

I noticed that the SLIP-0084 (BIP84) standard appears to have been removed from the repository. I would like to inquire about the reasons behind this decision. BIP84 is an important standard for defining SegWit (Segregated Witness) addresses, and it holds significant value for the cryptocurrency community and developers.

I have a few questions regarding this:

Why was SLIP-0084 removed? Is there a specific reason for this action?
If it has been removed, does this mean that the BIP84 standard is no longer supported?
If BIP84 is still supported, where can I find the latest version of the standard?
Thank you very much for your time and assistance.

Looking forward to your response.

**Comment by prusnak** [comment]
There was never a SLIP-84 standard.

BIP-84 is supported.
