### ISSUE TITLE
SLIP-0044: Add Ice Network coin

### ISSUE THREAD

**Issue by hoquangtrung** [satoshilabs/slips#1692]
Coin Name:
Ice Network

Coin Symbol:
ICE

Brief Description of the Coin and the Blockchain it Operates On:
Ice is the new global digital currency mined, owned, and operated by everyday users like yourself. Download our easy-to-use 📱 mobile app today!
Built on the Ice Open Network #ION, allowing it to process millions of TPS, positioning it among the fastest blockchains currently available. It is a native currency with its own blockchain.

Related Links or References:
https://ice.io/
https://github.com/ice-blockchain"

**Comment by prusnak** [comment]
Send a pull request, please.

**Comment by hoquangtrung** [comment]
ok sir
