### ISSUE TITLE
SLIP-0173 with regard to new CashAddr standard

### ISSUE THREAD

**Issue by sneurlax** [satoshilabs/slips#170]
Hi,

Bitcoin Cash's [CashAddr](https://github.com/Bitcoin-UAHF/spec/pull/21/commits/2ae8a404929ab87294a06379ae74d62d2f23d7e2) defines a specification for encoding legacy P2SH bitcoin addresses ("1...") with bech32, making addresses that look like: "bitcoincash:..." (as opposed to bitcoin's new bech32 address format, "bc1...")

**Comment by prusnak** [comment]
Bcash cashaddr has nothing to do with SLIP-173 as it is not following BIP-173.
