### ISSUE TITLE
registered purposes

### ISSUE THREAD

**Issue by 8de2fdb0** [satoshilabs/slips#1754]
I can't find any place that has a extensive list of taken BIP43 purposes.
It seems there are not too many and maybe there isn't really a need.

I searched through the BIPS and SLIPS issues and PR's and couldn't find anything related.

I could find https://github.com/bitcoin/bips/pull/523,  that does make a good point about BIP44 not being suited for account based blockchain implementations. 
But the reality is that a lot of wallets that support HD schemes and BIP39 backups use BIP44.

Adding a purpose registry can maybe allow other developers to come up with a better scheme for account based blockchains in the future, and would potentially prevent anyone using a already taken purpose or interpreting it wrong. 

I be willing to put in a MR for that if the reviewers of this repository share the opinion that a registry for purposes similar to SLIP44 for coins will be a good place for reference for wallet implementations.

**Comment by prusnak** [comment]
> I be willing to put in a MR

OK, let's discuss in the MR you create.
