### ISSUE TITLE
Add MarteXcoin

### ISSUE THREAD

**Issue by marcianovc** [satoshilabs/slips#177]
180   | 0x800000b4 | [MarteXcoin](http://martexcoin.org)

`https://github.com/martexcoin/slips/commit/8761667e5af18bca48712b5151fd57d7fdf10646`

**Comment by prusnak** [comment]
Added in 01ee04eaf5c070ec52d95c28e7aa84af41d5e15e

**Comment by marcianovc** [comment]
Thanks @prusnak
