### ISSUE TITLE
slip-0044.md misses currency abbreviations

### ISSUE THREAD

**Issue by morriswinkler** [satoshilabs/slips#178]
The List: Registered coin types within slip-0044.md is missing the currency abbreviations lice BTX ETH XRP ... and so on.

**Comment by prusnak** [comment]
Feel free to open the pull request adding the abbreviations. Thank you!

**Comment by morriswinkler** [comment]
I like to ref issues within my PR's and close them when they are done. But nevertheless, i already started on a PR. 

@prusnak I figured that most people use the word symbol instead of abbreviation, any objections?

**Comment by prusnak** [comment]
What is word symbol?

**Comment by prusnak** [comment]
Ah, I get it. You mean the word "symbol", not "the  word symbol". Ok, no
objections.
