### ISSUE TITLE
Shamir scheme backup like BIP39. And the Bitcoin Trezor supporting?

### ISSUE THREAD

**Issue by Perlover** [satoshilabs/slips#18]
Hello,

I described my idea here:

https://bitcointalk.org/index.php?topic=1497943.0

I am very interested by your opinion :)

Best regards, Perlover

**Comment by prusnak** [comment]
There is already a code for this here: https://github.com/trezor/python-mnemonic/blob/master/mnemonic/shamir.py

It just needs more thinking and writing a standard. Will do that in the future (most probably not near future, though).

**Comment by prusnak** [comment]
As written above. This is in progress. Just needs more time.
