### ISSUE TITLE
slip-0044 address space

### ISSUE THREAD

**Issue by morriswinkler** [satoshilabs/slips#180]
Is there a reason why the address space starts that big ( example BTC: 0x80000000 )?

It just breaks int32, unit32 would work, but on some architectures/languages that might become unhandy. 

That space includes (2^31)-1 coin derivations, a few less leading bits would do it too.

**Comment by morriswinkler** [comment]
Ok, I see 0x80000000 is like a base used for other values as well, so I guess shifting it out is the way to go.

Still is there a reason for that prefix?

**Comment by prusnak** [comment]
BIP44 mandates hardened derivation for coin_type. That's why all values need to have the highest bit set to 1.

**Comment by prusnak** [comment]
If your library does not use highest bit to indicate hardened derivation, just use the index from the first column.

**Comment by morriswinkler** [comment]
Thanks
