### ISSUE TITLE
Requirement for Unique SLIP-0173 Bech32 Prefixes?

### ISSUE THREAD

**Issue by JeremyParish69** [satoshilabs/slips#1836]
Is it required that SLIP-0173 bech32 addresses be unique?
For what I can tell, there is at least strong recommendation to keep these uquine per chain (or at least per project, since some chain re-use tehe same prefix for their testnet and mainnet).
I generally try to ensure the Cosmos Chain Registry agrees with these SLIP registries for SLIP-0044 and SLIP-0173, however we are starting to see cases where some projects are using bech32 prefixes (in their already-launched mainnet) that have already been registered here by other projects. First, there was terra classic and terra 2, but now there is also zen protocol and zenrock.

Would we be able to register two lines with the same prefix in SLIP-0173?, e.g.,
'terra' | Terra Classic
'terra' | Terra 2
or
'zen' | Zen Protocol
'zen' | Zenrock

**Comment by prusnak** [comment]
I am not going to add the duplicates into the list. If a project wants to use a prefix, they should register here first.
