### ISSUE TITLE
SLIP-0044 normal child keys versus hardened child keys

### ISSUE THREAD

**Issue by morriswinkler** [satoshilabs/slips#185]
Referencing to #180, I actually understood now that the coin-type definitions for BIP-0044 are all defined as the hardened version of the coin-type ID.

So I guess.

hardened:

index | hexa       | symbol | coin
------|------------|--------|-----------------------------------
0        | 0x80000000 | BTC    | [Bitcoin](https://bitcoin.org/)

Versus nonhardened:

index | hexa       | symbol | coin
------|------------|--------|-----------------------------------
0     | 0x0 | BTC    | [Bitcoin](https://bitcoin.org/)

Please, correct if I am wrong with that assumption. 

Otherwhise I would propose to state that clearly within SLIP-0044 and BIP-0044, since this is not very clear to the reader.

**Comment by prusnak** [comment]
BIP44 states very clearly that coin_type is hardened: 

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

```
m / purpose' / coin_type' / account' / change / address_index

Apostrophe in the path indicates that BIP32 hardened derivation is used.
```

SLIP44 is an extension to BIP44, so I assume that reader of SLIP44 is already familiar with BIP44.

**Comment by morriswinkler** [comment]
Thanks for the long discussion. 👎 

And yes it is clear that this is the hardened version, but it nowhere states what the nonhardened version is. From reading BIP32 I suppose that it is 0x0. Which at this point is still an assumption.
My original question was not answered. 

Leaving things open for interpretation within a spec makes it difficult to have consistent implementations.

**Comment by prusnak** [comment]
Look, if you want to improve the wording, send a pull request and we can
frame our discussion over particular proposal.

**Comment by prusnak** [comment]
Also you can't use the non-hardened derivation for coin_type at all. If
it's not obvious, send the PR.
