### ISSUE TITLE
SLIP-0016: make pwdreader.py a part of python-trezor?

### ISSUE THREAD

**Issue by thibault** [satoshilabs/slips#207]
Hi,

I'm not sure if this is the place to ask for such a question, so forgive me if I'm not using the correct channel.

I started to implement a python command-line tool that share some of the features of SatoshiLabs' password manager.

I stumbled upon [SLIP-0016](https://github.com/satoshilabs/slips/blob/master/slip-0016.md) and saw that there is [already a python implementation](https://github.com/satoshilabs/slips/blob/master/slip-0016/pwdreader.py).

It seems to me such code could be handy for third-party developers, and could be moved into the [python api](https://github.com/trezor/python-trezor), maybe in the `tools` subdirectory. Is such a thing a project? Would you be interested on a PR?

Moreover, I could not find any license information associated with the code in `pwdreader.py`, so I don't know if I may use this code as a base for my own tool?

Thank you.
Thibault.

**Comment by prusnak** [comment]
Thanks, moved to https://github.com/trezor/python-trezor/blob/master/tools/pwd_reader.py

Licensed under LGPLv3 like the rest of the package.
