### ISSUE TITLE
SLIP-0039 Should master secret length be auto detected or provided at recovery time

### ISSUE THREAD

**Issue by Sharpiro** [satoshilabs/slips#218]
```
5 byte/40 bit secret
    82 bits
    9 words
6 byte/48 bit secret
    90 bits
    9 words
```
If I have generated a share where the master secret is for example, 5 bytes(40 bits) or 6 bytes(48 bits), a valid multiple of 8 bits, I will end up creating a secret share of size 82 bits and 90 bits respectively when accounting for additional checksum data and index/threshold data.

However, both of these secret sizes will create a secret share of 9 words.  This means that when using these shares as input into the master secret recovery function, there is not enough information to automatically determine the secret size 100% of the time (at least so far as I can tell).  There is only enough information to detect that the secret size is "at most X bits", meaning given random data size, you would only be accurate 50% of the time.

Assuming I haven't overlooked something, I see there being 3 possible options to deal with this:
1. Auto-detect the share size, and if the checksum fails, just run the function again with a larger expected master secret size.  This would mean it would always take 1-2 times to work.  But this seems a little sloppy.
2. Add an additional block of data to each secret share saying how large the master secret truly is.  The downside of this is we would need 1-2+ bytes in the secret shares just to tell us how long the original master secret was.  The upside is that since we can already detect the index/threshold from the given secret, it would be nice to detect the master secret size as well.
3. Have the user provide the expected master secret size at the time of master secret recovery.  This is clean, but is more prone to user error and requires additional input.

I personally like options 2 and 3, but please let me know what you think or if there are other options and solutions that would be better.

**Comment by prusnak** [comment]
@onvej-sl can you have a look?

**Comment by onvej-sl** [comment]
You are right, the structure doesn't specify the length of the master secret and the length can't be determined unambiguously from the number of words. It has to be known a priori (option 3 is the correct one).

Typical usecase of the scheme is a generation of a deterministic wallet. In that case you most probably use 128 or 256 bit master secret.
