### ISSUE TITLE
Litecoin testnet values in Slip132 correct?

### ISSUE THREAD

**Issue by dan-da** [satoshilabs/slips#319]
Slip132 defines

    Litecoin Testnet	0x0436f6e1 - ttub	0x0436ef7d - ttpv	P2PKH or P2SH

yet the [litecoin source code](https://github.com/litecoin-project/litecoin/blob/f1e1ab4ebcd59b5bff7017539da92001f8b7594f/src/chainparams.cpp#L243) has for testnet:

```
        base58Prefixes[EXT_PUBLIC_KEY] = {0x04, 0x35, 0x87, 0xCF};
        base58Prefixes[EXT_SECRET_KEY] = {0x04, 0x35, 0x83, 0x94};
```

so where is 0x0436f6e1 and 0x0436ef7d coming from?

See discussion [here](https://github.com/dan-da/hd-wallet-derive/issues/6).

edit: the same applies to Litecoin mainnet:

```
        base58Prefixes[EXT_PUBLIC_KEY] = {0x04, 0x88, 0xB2, 0x1E};
        base58Prefixes[EXT_SECRET_KEY] = {0x04, 0x88, 0xAD, 0xE4};
```

vs

```
Litecoin	0x019da462 - Ltub	0x019d9cfe - Ltpv	P2PKH or P2SH
```

Where the does the discrepancy come from?   thx.

**Comment by prusnak** [comment]
Litecoin community kept using both xpub/Ltub prefixes because they just don't care about having one prefix. See also 3/M-prefix fiasco for their P2SH addresses. I recommend every wallet to use the M-prefix and values from SLIP-0132.

**Comment by dan-da** [comment]
thx for clarification.  It seems like slip132 should at least make note of these LTC issues though.  That would've saved me time for sure.

Trying to understand the matter, I dug up the following quotes:

From: https://github.com/pooler/electrum-ltc/issues/52

> Officially Litecoin uses the same BIP32 prefixes as Bitcoin (see here). This is on purpose, as it makes sense to generate addresses for multiple cryptocurrencies from a single master key.
> 
> The Ltub/Ltpv prefixes were independently made up by the author of the website bip32.org before BIP32 was even discussed by the Litecoin development team. As far as I know they were never officially supported, but unfortunately some developers who believed they were official used them in their software, contributing to the confusion.

and from https://github.com/iancoleman/bip39/issues/96

> Looks like litecoin has been a bit inconsistent with the different options, but in the end litecoin core seems to be using xprv xpub so I'll change the default litecoin network constants to reflect that with an option to switch to Ltub. It's a bit of a mess since there's a lot of implementations out there using Ltpv Ltub.
