### ISSUE TITLE
SLIP0039 terminology

### ISSUE THREAD

**Issue by jakubtrnka** [satoshilabs/slips#324]
I suggest slightly improving the terminology in this document. The data structure is defined as {N, I, M, SSS, C}, where the SSS part (being acronym for Shamir's secret share) is called "Share" and the actual cryptographic Share is produced by hashing serialized data structure. The words-encoded data structure, although this is not directly stated in this document, might also, for convenience, be called share by users. This is quite confusing.
I suggest to call the current SSS part in data structure as "share enthropy", the data structure itself as "share object" or "share mnemonic" and the final hash as "raw share" or "shamir's secret share".

**Comment by prusnak** [comment]
We dropped the KDF because it eliminates M-of-N usecases where M < N, so this ambiguity is now gone.
