### ISSUE TITLE
Testnets shouldn't be all 1

### ISSUE THREAD

**Issue by psionic81** [satoshilabs/slips#34]
It makes literally no sense whatsoever.. if we want Jaxx (or any other wallet) to have testnet support, we certainly aren't going to derive all of the testnets off the same HD branch. Maybe not a huge deal for (most) current blockchains, but ETH/ETC has already caused conflicts in this way with competing address space on an HD tree.

ETH testnet and ETC testnet should not be from branch 1. Similarly, and other further coins that share the same bitcoin-like configurations in order to preserve database/blockchain compatibility should also have their own HD branch paths.

So, what I'd propose is to make BTC the special case (with perhaps a list of wallet-compatible testnets) and augment this spec with the following:

All testnets are the base coin's HD branch # + (some other large number)

base + 177337 or some such thing :)

**Comment by prusnak** [comment]
I really don't see why there is a problem. Can you give one particular reason? (Saying "should not" 5 times in a row is not a valid reason).

**Comment by slush0** [comment]
Separate paths for coins are there mostly for privacy concerns and address reuse. As far as testnets does not use real coins, I don't see any reason why complicate things in any way.

**Comment by dangershony** [comment]
If you really find you need a testnet coin-type perhaps just create one for that specific coin? (like with bitcoin)
I did't find any need for a testnet HD path (yet)

**Comment by psionic81** [comment]
etc and eth, if they had the same hd paths would result in the same addresses, which is completely confusing for users sending to addresses.

we want to give testnet support for as many as we need to, internally or not. it'd just be nice to have a standard..

**Comment by prusnak** [comment]
If I give you address such as 0x7a6366ecfcaf0d5dcc1539c171696c6cdd1eb8ed how do you know whether it is ETH or ETC address? You don't - it is valid for both networks.

I don't see why users should be confused when they see the same address as they are really valid in both networks. (Not to mention testnet is supposed to be used by developers, which probably know what they are doing).

**Comment by psionic81** [comment]
paul.. think about it. I'm talking about exactly that *from the wallet user's persepective*. there's a reason etc and eth have different ids here, and as such, different testnets for etc and eth need different addresses.

**Comment by dangershony** [comment]
@psionic81 the main motivation behind BIP32 is easily create backups of wallets and BIP44 extends this to altcoin.
Do you have a need to backup thousands of testnet wallets?

**Comment by psionic81** [comment]
I would say, from what we're working on here, the answer to that question a resounding "yes" @dangershony  :)

Consider my position. Wallet making, but still needing to educate.

If I could distribute (and have others that follow our lead compatible in the future no less, which is all that I'm trying to get the standard solidified with peeps with) a wallet that was still fully functional, allowed people to test balances and apis, with custom connections to endpoints, communities like dash, wouldn't have to worry about their tester pools running different os, versions of blockchains, synch times and all that and just hop on and do the basic functionality testing that literally every single blockchain I've worked with has in common (tx list, balances, local signing w/ broadcasting).

In a school, a crypto-economics prof. could distribute a wallet to their students, say "here's what blockchain we're looking at today'.


'cause they're still fully functional, right? it's literally just the fact that they are next to inaccessible for even the most ardent supporters, and that means less eyes and less educational capabilities because the cost center for doing so is simply too high.


so yeah. I'd love to have every single coin here associated with a testnet, *simply by a standard of a linear addition to the base registry value*. it's easy, costs no-one, completely future compatible and the sooner we get it solid, the sooner it will never be an issue for the use-cases outlined above, re: compatibility (which is, ofc, why we're working on standards)


I hope that this has been enough of an insight surrounding the consumer facing projections I've done about the wallet space, and all the opportunities therein :)

**Comment by greatwolf** [comment]
I know this is quite old issue but I ran into a similar issue which led me to same question that @psionic81 raised. I wanted to implement TESTNET support for Dash and possibly others on KeepKey and I find myself running into the problem of not being able to disambiguate between TESTNET for Dash or Bitcoin or some other utxo-type altcoin.

Here's what I'd propose for resolving this issue, feedback welcome. The 1st left-most bit is already used to indicated harden-ness. Why not use the 2nd left-most bit for `coin_type` to indicate whether it's for TESTNET or not?

So for example, for Dash the TESTNET path would start with `m/44'/1073741829'/0'/...` (`1073741829` being `5` as `int32` with 2nd left-most bit set). For Dogecoin it would use as TESTNET the path `m/44'/1073741827'/0'/...`.

Even with 2 bits reserved in this fashion there's still enough space left over for > 1billion coins.

**Comment by prusnak** [comment]
@greatwolf what exactly is your problem?

**Comment by andrewkozlik** [comment]
What @prusnak meant to say is what problem are you trying to solve. What exactly do you mean by "disambiguate between TESTNET for Dash or Bitcoin" and why do you need it?

**Comment by greatwolf** [comment]
Well in my case, concretely, the original KeepKey chrome client uses a two-way reversible LUT where you can look up coin name given slip44 index and visa-versa, given slip44 look up the coin name. Problem is through out the codebase some places use slip44 to look up coin and get the corresponding config while other places uses the coin name string. Depending on call context, only the slip44 index may be available or visible.

Of course uniquely looking up a coin config/profile by slip44 is not possible if multiple coins use the same slip44 index.

**Comment by prusnak** [comment]
If you don't have the source then you are out of luck, sorry.
