### ISSUE TITLE
SLIP-044: constant reusage

### ISSUE THREAD

**Issue by fanatid** [satoshilabs/slips#345]
@prusnak if coin removed from list or allocate new constant, can we mark previous constant as not available for another coins? I often see such issues in [bitcoinjs/bip44-constants](https://github.com/bitcoinjs/bip44-constants/), for example in last PR: https://github.com/bitcoinjs/bip44-constants/pull/19
`BTV` changed their constant at February in https://github.com/satoshilabs/slips/pull/216 and at June old constant was reused by `GOD` -- https://github.com/satoshilabs/slips/pull/298 =(

Can we add note to SLIP that constant can not be reused? I think this also will be good left coin with old value in table but mark coin as crossed out with symbol ~

**Comment by prusnak** [comment]
If altcoins want to play stupid games by not using the first available
number, they deserve to win stupid prizes. I am not going to pay extra
effort to detect all historical collisions.
Feel free to help if you have time to spend on this. Just subscribe to
repo to receive notifications for all upcoming pull requests and review
the slip44 changes.

**Comment by fanatid** [comment]
Thanks for comment @prusnak I already subscribed a long time for this repo, but usually ignore notifications =( I'll try review them in future. All what I proposed is not remove already used constants from list, like what was done with `0x8000004a` (sorry, I do not remember what this is a coin was).
