### ISSUE TITLE
SLIP-0044 adding OOT

### ISSUE THREAD

**Issue by emmnx** [satoshilabs/slips#347]
Hi, we need to add [OOT](https://utrum.io/ootcoin/) to Coinomi wallet; and they asked to include the coin in the SLIP-0044. 
The values would be the same as for KMD, since our code is the same, just independent chain. 
How should we proceed? Would the index number be the same?
Thanks in advance.

**Comment by prusnak** [comment]
No, the value should be different.

**Comment by emmnx** [comment]
So is it an arbitrary number? I noticed that it doesn't follow a sequence order. @prusnak

**Comment by prusnak** [comment]
Pick first free number

**Comment by emmnx** [comment]
Thanks!
