### ISSUE TITLE
SLIP-0044 Questions

### ISSUE THREAD

**Issue by CruiseMan** [satoshilabs/slips#351]
Can someone explain to me next questions regarding [slip44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) 

1. What `hexa` stands for ?
2. How we got `0x8000003c` if in  javascript converting`(60).toString(16)` gives `"3c"`
3. What is the right way to convert `60` to `0x8000003c` and in opposite direction in javascript ?

**Comment by jhoenicke** [comment]
Since private derivation is used, 2^31 should be added for the hex field (see bip32 spec), e.g., `(60 + (1<<31)).toString(16)`

**Comment by CruiseMan** [comment]
@jhoenicke @prusnak Thank you for clarification, but how to convert `0x8000003c` => `60` ?.

**Comment by jhoenicke** [comment]
Convert from hex to decimal and subtract (1<<31).

**Comment by CruiseMan** [comment]
What i'm doing wrong ? `parseInt("0x8000003c", 16) - (1<<31)` => `4294967356`

**Comment by jhoenicke** [comment]
Javascript weirdness.  try `parseInt("0x8000003c", 16) - ((1<<31)>>>0)`

**Comment by CruiseMan** [comment]
@jhoenicke Danke
