### ISSUE TITLE
BIP-44 coin type for non-secp256k1 coin

### ISSUE THREAD

**Issue by carryforward** [satoshilabs/slips#39]
My project, Factom, has been contacted by a wallet manufacturer to create a BIP-44 standardized compatible derivation.  The only snag is that our internal token uses ed25519 signatures rather than the BIP-32 standard secp256k1.

I don't see any examples of another project on the BIP44 list having this problem as a precedent.  Monero uses curve25519 and is listed here, but their code shows them using the electrum style seed.
https://github.com/monero-project/monero/blob/master/src/mnemonics/electrum-words.h#L62

nxt also used curve25519 and uses their own word list: 
https://github.com/Blackcomb/nxt/blob/master/html/ui/js/crypto/passphrasegenerator.js#L43

BIP44 only uses hardened keys, so being able to publicly derive new pubkeys is off the table regardless.  

Ed25519 can take in any length value for its private key, so it doesn't matter BIP44 generates 32 or 33 byte long keys.

Koinify used BIP-32 when they coded up the token sale: https://github.com/FactomProject/FactomDocs/tree/master/token_sale

Also, our project has two distinct tokens, one trade-able and the other not.  They are Factoids and Entry Credits.  Would it make sense to have a registered coin type for each?

**Comment by prusnak** [comment]
You should not use BIP-32 HD scheme for Ed25519 based cryptography.
