### ISSUE TITLE
bip44-constants

### ISSUE THREAD

**Issue by fanatid** [satoshilabs/slips#4]
Can you add link to JavaScript module [bip44-constants](https://github.com/bitcoinjs/bip44-constants) ([npm](https://www.npmjs.com/package/bip44-constants)) to [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)? Thanks!

**Comment by fanatid** [comment]
of course :) #5

**Comment by prusnak** [comment]
Closing
