### ISSUE TITLE
Add HDAC

### ISSUE THREAD

**Issue by HdacTechTeam** [satoshilabs/slips#419]
240   | 0x800000f0 | HDAC   | [HDAC](https://www.hdactech.com)

https://github.com/HdacTechTeam/slips/commit/f5093b262a72cdd2e40bd3d2ee3fca7f86da447a#diff-0f4184ad95ed5fe9c360cdd0e30bd17b

**Comment by hackmod** [comment]
why don't you make a pull request?

**Comment by prusnak** [comment]
Make a pull request
