### ISSUE TITLE
SLIP-0013: Worked example issue?

### ISSUE THREAD

**Issue by angelix** [satoshilabs/slips#526]
It seems there are some issues in the Worked example and particular in point 4.

For example in 5. A' = 2637750992
But if we set the highest bit number to 0 (unharden) in 4. A = 490267344 not 221831888 as mentioned.
Maybe miss something?

**Comment by prusnak** [comment]
The numbers were wrong. Fixed in 4131f572653db15463ced4fa702485da37ea6076
