### ISSUE TITLE
SLIP-0039: Social Key Recovery Standards at #RebootingWebOfTrust on March 1st-3rd in Barcelona

### ISSUE THREAD

**Issue by ChristopherA** [satoshilabs/slips#534]
I host a design workshop called #RebootingWebOfTrust, and we are meeting in Barcelona on March 1st-3rd (our 8th design workshop!). There will be a team forming of people from different companies (including engineers from HTC that implemented SSS on the Exodus smartphone, and the author of one of the better SSS libraries @dsprenkels) that will be there to work on improving standards around social key recovery. 

We would really like some of the Trezor people and others involved with SLIP-0039 effort to participate. You can register at https://rwot8.eventbrite.com and I can offer discounts or partial scholarships for independent developers and academics if you can't afford the full price for the event.

So far, four advance readings on Social Key Recovery have been submitted:

**A New Approach to Social Key Recovery**
https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/topics-and-advance-readings/social-key-recovery.md
by Christopher Allen @christophera and Mark Friedenbach @maaku
"The goal of social key recovery is for the user to specify groups of individuals that together possess the ability to recover the root secret of a wallet."

**Security Considerations of Shamir's Secret Sharing**
https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/topics-and-advance-readings/security_shamirs.md
by Peg @ameba23
"Issues with private key management often pose barriers to the adoption of empowering decentralised technologies and this is exactly what this project aims to address. ... Threshold-based secret sharing schemes provide a powerful tool to address the private-key custody problem. There are promising solutions to the issues explored in this article. However, we have focussed here mainly on technical limitations of such schemes."

**Implementing of threshold schemes**
https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/topics-and-advance-readings/implementing-threshold-schemes.md
by Daan Sprenkels @dsprenkels
"Shamir secret sharing is a method to split secrets into shares, and to later recombine them. However, it does not feature integrity protection of the secret. This article elaborates on Feldman VSS and Pederson VSS, which do protect the message integrity. Furthermore, we show how hashing the shares also protects the message integrity, but is vulnerable to a cheating dealer."

**Social Key Recovery Design and Implementation**
https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/topics-and-advance-readings/Socia_%20Key_Recovery_design_implentation.md
by Hank Chiu @hankchiuhc, Hankuan Yu, Justin Lin & Jon Tsai
"Social Key Recovery aims to provide an alternative and interesting way to help user backup their cryptocurrency mnemonic phrase. Currently user needs manually to write down all his mnemonic phrase on a piece of paper and locks it in a safe, which is troublesome to user. To solve user’s pain in backup, Social Key Recovery tries to propose a social way to help user backup their mnemonic phrase."

**Comment by prusnak** [comment]
First of all, thank you for the invitation. You have to realize this is on very short notice. If you really liked to see some of us attending, you should have invited us much earlier. However, if you can arrange a free ticket or two, I'll ask my colleagues, whether they want to attend.

**Comment by ChristopherA** [comment]
We were not sure we’d have critical mass of people until this week. And yes we can work out something for the right people.

**Comment by Sharpiro** [comment]
I think this important topic should also be discussed:
https://github.com/Sharpiro/go-slip-0039/blob/master/docs/horcruxes.md

**Comment by prusnak** [comment]
@ChristopherA will contact you via email
