### ISSUE TITLE
Add slip-0011 test vector

### ISSUE THREAD

**Issue by karel-3d** [satoshilabs/slips#568]
Split 0011 (CipherKeyValue description) could use some test vectors, on "all all all" (slip-014) would be ideal :) but any other would be good too

**Comment by karel-3d** [comment]
This seems to be working as a test vector

https://github.com/trezor/python-trezor/blob/master/trezorlib/tests/device_tests/test_msg_cipherkeyvalue.py#L29

**Comment by prusnak** [comment]
https://github.com/satoshilabs/slips/commit/ab5ce4c3df56cab04518afe2d82880763dc663d2
