### ISSUE TITLE
slip-0039 Road Map

### ISSUE THREAD

**Issue by itsMikeLowrey** [satoshilabs/slips#609]
Is there a timeline for when this slip will become accepted? or an estimate of how much the spec might change moving forward? I would like to build some implementations and just wanted to check in how solid the spec is currently and when it will be accepted.

**Comment by prusnak** [comment]
Standard is more or less final. We'll be adding that to Trezor Model T soon. About the acceptance, we'll see, but I guess more wallets will adopt that eventually.
