### ISSUE TITLE
SLIP-0039 Credit?

### ISSUE THREAD

**Issue by ChristopherA** [satoshilabs/slips#666]
@andrewkozlik, can you credit Mark Friedenbach @maaku and I for the two level methodology, or mention the #rwot8 paper https://github.com/WebOfTrustInfo/rwot8-barcelona/blob/master/topics-and-advance-readings/social-key-recovery.md , or both?

**Comment by andrewkozlik** [comment]
Done https://github.com/satoshilabs/slips/commit/733061dbb04e42d4e1abf85ec7eb5cccbf9f25eb.
