### ISSUE TITLE
SLIP-0039: Need for Key Generation Date (aka Birthday)

### ISSUE THREAD

**Issue by ChristopherA** [satoshilabs/slips#695]
Both the recovery words used by Lightning Labs, and the BIP-0039 recover words used by bitcoinj use a key generation date for efficiency, otherwise scanning the blockchain takes too long for starting up. I suggest that this possible in the spec with SHOULD (but not MUST) requirement.

cc/ @roasbeef re @lightningnetwork
cc/ @msgilligan re: @bitcoinj

-- Christopher Allen

**Comment by ChristopherA** [comment]
CCing these people that have also been working C implementations of the Blockchain Commons version of SLIP-0039:

cc/ @justin52tw of @Seclabs-htc
cc/ @howech of @Unchained-Capital 
cc/ @maaku of @BlockchainCommons

I know that HTC may also be interested in encoding the key generation date as they also are implementing a full node on mobile and the info may help them scan the blockchain more efficiently.

**Comment by justin52tw** [comment]
@ChristopherA 
Ideally the Birthday can reduce the scan time(Scan after the birth), am I same tone with yours?

**Comment by ChristopherA** [comment]
@justin52tw:

Exactly, which is how bitcoinj (the Java based version of bitcoin) uses it to help with faster SPV & pruned node updating. (@msgilligan, correct?) Unfortunately bitcoin-core does not support this yet, but might be worthy of a PR.

I presume this is why Lightning Labs version of LN uses it, but they use it to speed up Neutrino (@roasbeef, correct?)

— Christopher Allen

**Comment by prusnak** [comment]
This has been discussed over a million times. Birthday is a bad optimization and we are not adding it.

**Comment by maaku** [comment]
Respectfully, I think you should look into the performance of rescan times on various nodes and hardware configurations. Rescans from genesis can take DAYS and are simply not an option in many contexts.

**Comment by prusnak** [comment]
Respectfully, you should read a comment before replying to it. I am not suggesting rescans from genesis, but rather from a fixed date. If your wallet being used in 2030 can't sync from 2019, I highly doubt it can sync from let's say 2025.

**Comment by maaku** [comment]
I’m not sure I follow the argument that you are giving. If your wallet in 2030 can’t sync from 2019, that is *exactly* why every modern wallet has the ability to specify birthday on import. So you don’t have to sync from 2009, or 2019, or 2025 or any other arbitrary date. This is an extremely vital performance optimization that makes key import a viable option at all on many clients.

**Comment by ChristopherA** [comment]
Suppose that we keep the base format as is, but add some standard way to extend it with key metadata (which could include birthday) such that the metadata can also be secret shared. This has the advantage of also allowing for some future proofing.
