### ISSUE TITLE
SLIP-0044: Duplicated hexa value 0x800000d5

### ISSUE THREAD

**Issue by s60912frank** [satoshilabs/slips#926]
Hi, I found there is a duplicated entries:
index | hexa       | symbol | coin
------|------------|--------|-----------------------------------
213   | 0x800000d5 | XSPEC  | [Spectrecoin](https://spectreproject.io/)
214   | 0x800000d5 | MONK   | [Monkey Project](https://www.monkey.vision)

Was this intended or by mistake? Thanks!
Commit to reference: 6168c75c64db3978d103163ba95b9307e422ab05

**Comment by prusnak** [comment]
It was a typo, fixed in 7291e0884522bc285c8d0457048ae6a18d9a0dbd
