### ISSUE TITLE
Support for NEO (ANT Shares) coin

### ISSUE THREAD

**Issue by kim0** [satoshilabs/slips#94]
I wanted to know what my private key would my seed-phrase generate for NEO. But since I could not find NEO in the list of registered coins, I figure this is not possible at this time?

What's the process for adding a new coin? i.e. Can I request adding NEO

**Comment by prusnak** [comment]
Process for adding new coin is to ask coin developers to add support for TREZOR. That is the first step.

**Comment by saleemrashid** [comment]
@prusnak I understood this as "process for adding a new coin to SLIP-0044"

**Comment by kim0** [comment]
I'm confirming that I meant SLIP-0044

**Comment by prusnak** [comment]
They way how to add entries to SLIP-0044 is to create a pull request.

**Comment by kim0** [comment]
mm I guess a better way to ask is, what "authority?" allocates a certain
number for a certain coin. i.e. I'm not affliated with Monero for example,
who can I ask to allocate them a number? After the number is allocated, the
pull-request is the easy part.

I'm guessing I cannot just pick a random number out of thin air, and send a
PR for it ?!

Thanks, and sorry for not being the clearest

**Comment by prusnak** [comment]
SLIP-44 document IS the authority that allocates numbers. You should pick the first free number to have it assigned.
