### ISSUE TITLE
SLIP-44: Wrong HexAddress for Defcoin

### ISSUE THREAD

**Issue by bu5hm4nn** [satoshilabs/slips#97]
Just glanced over the list and noticed that slips/slip-0044.md:177 lists an incorrect HexAddress for Defcoin. Looks like a copy-paste error from Ripple two lines above. Should be 0x80000000 + 1337 = **0x80000539**.

**Comment by prusnak** [comment]
Fixed in https://github.com/satoshilabs/slips/commit/f3aa073cf208d3b98d29ca42eef1dda5bdb51eee
